export const copy = {
  brand: {
    name: 'KindSpark',
  },
  onboarding: {
    welcomeSubtitle: 'Small actions can create big change.',
    getStarted: 'Get Started',
    valueHeadline: 'A positive habit can transform your day.',
    continue: 'Continue',
    enableNotifications: 'Enable Notifications',
    notNow: 'Not now',
    saveTime: 'Save Time',
    seeMyAction: 'See My Action',
    notificationTimeTitle: 'When should we remind you?',
    notificationTimeSubtitle:
      'Pick a time for your daily kindness nudge. You can change this later in Settings.',
    notificationTimeSelected: 'Selected',
    signInRequired: 'You need to be signed in.',
    notificationsDenied:
      'Enable notifications in system settings to get daily reminders.',
    savePreferencesError: 'Could not save your preferences.',
  },
  tabs: {
    today: 'Today',
    progress: 'Progress',
    history: 'History',
    settings: 'Settings',
  },
  today: {
    greetingMorning: 'Good morning',
    greetingAfternoon: 'Good afternoon',
    greetingEvening: 'Good evening',
    didIt: 'I did it ✨',
    skip: 'Skip',
    newIdea: 'New idea',
    amazing: 'Amazing ✨',
    loading: 'Loading your kindness…',
    offline: 'You are offline. Changes will sync when you reconnect.',
    offlinePending: 'Offline — your action will sync when you’re back online.',
    offlineCached: 'Offline — showing your last cached suggestion.',
    completedTitle: 'You showed kindness today',
    completedSubtitle:
      'Your streak counts for today. Come back tomorrow for a new suggestion.',
    skipHint: 'Skipped this one — pick another idea when you’re ready.',
    emptySuggestion: 'No suggestion available right now.',
    loggedFor: 'Logged for',
  },
  progress: {
    title: 'Your progress',
    currentStreak: 'Current streak',
    days: 'days',
    day: 'day',
    completed: 'Completed',
    skipped: 'Skipped',
    completionRate: 'Completion rate',
    achievements: 'Achievements',
    seeAll: 'See all',
    noStreakTitle: 'Start your streak today',
    noStreakBody: 'Complete today\'s kindness on the Today tab to start your streak.',
    retry: 'Tap to retry',
    milestoneReached: 'Milestone reached',
    streakSubtitle: '{n}-day kindness streak',
    streakSubtitleOne: '1-day kindness streak',
    nextMilestoneHint: '{n} more {unit} until your {m}-day milestone.',
    dayUnit: 'day',
    daysUnit: 'days',
  },
  history: {
    title: 'History',
    empty: 'Your kind moments will show up here.',
    today: 'Today',
    yesterday: 'Yesterday',
    daysAgo: '{n} days ago',
    statusDone: 'Done',
    statusSkipped: 'Skipped',
    retry: 'Tap to retry',
  },
  completion: {
    headline: 'Amazing ✨',
    messages: [
      'You made someone\'s day better ✨',
      'One kind action completed 🌱',
      'Small actions create big change 💛',
    ],
    currentStreak: 'Current streak',
    completedActions: 'Completed',
    seeProgress: 'See my progress',
    seeHistory: 'See history',
    close: 'Close',
  },
  settings: {
    title: 'Settings',
    notifications: 'Notifications',
    reminderTime: 'Reminder Time',
    sound: 'Sound',
    vibration: 'Vibration',
    privacy: 'Privacy',
    terms: 'Terms',
    about: 'About',
    rateApp: 'Rate App',
    on: 'On',
    off: 'Off',
    saved: 'Settings saved.',
    signOut: 'Sign out',
    dailyReminder: 'Daily reminder',
    saveChanges: 'Save changes',
    remindersOff: 'Reminders are off. You can still open the app anytime.',
    comingSoon: 'Coming soon',
    loadError: 'Could not load settings.',
    saveError: 'Could not save settings.',
  },
} as const;
