export const copy = {
  brand: {
    name: 'KindSpark',
  },
  onboarding: {
    welcomeSubtitle: 'Small actions can create big change.',
    getStarted: 'Get Started',
    valueHeadline: 'A positive habit can transform your day.',
    continue: 'Continue',
    enableNotifications: 'Enable Notifications',
    notNow: 'Not now',
    saveTime: 'Save Time',
    seeMyAction: 'See My Action',
  },
  tabs: {
    today: 'Today',
    progress: 'Progress',
    history: 'History',
    settings: 'Settings',
  },
  today: {
    greetingMorning: 'Good morning',
    greetingAfternoon: 'Good afternoon',
    greetingEvening: 'Good evening',
    didIt: 'I did it ✨',
    skip: 'Skip',
    newIdea: 'New idea',
    amazing: 'Amazing ✨',
    loading: 'Loading your kindness…',
    offline: 'You are offline. Changes will sync when you reconnect.',
  },
  progress: {
    title: 'Your progress',
    currentStreak: 'Current streak',
    days: 'days',
    day: 'day',
    completed: 'Completed',
    skipped: 'Skipped',
    completionRate: 'Completion rate',
    achievements: 'Achievements',
    seeAll: 'See all',
    noStreakTitle: 'Start your streak today',
    noStreakBody: 'Complete today\'s kindness on the Today tab to start your streak.',
    retry: 'Tap to retry',
  },
  history: {
    title: 'History',
    empty: 'Your kind moments will show up here.',
    today: 'Today',
    yesterday: 'Yesterday',
    daysAgo: '{n} days ago',
    statusDone: 'Done',
    statusSkipped: 'Skipped',
    retry: 'Tap to retry',
  },
  settings: {
    title: 'Settings',
    notifications: 'Notifications',
    reminderTime: 'Reminder Time',
    sound: 'Sound',
    vibration: 'Vibration',
    privacy: 'Privacy',
    terms: 'Terms',
    about: 'About',
    rateApp: 'Rate App',
    on: 'On',
    off: 'Off',
    saved: 'Settings saved.',
    signOut: 'Sign out',
    dailyReminder: 'Daily reminder',
  },
} as const;
