-- T-012: 50 curated kindness actions

insert into public.actions (title, description, category) values
  ('Compliment a stranger', 'Give someone a sincere, specific compliment today.', 'kindness'),
  ('Hold the door open', 'Hold the door for the next person behind you.', 'kindness'),
  ('Leave a kind note', 'Write a short encouraging note and leave it where someone will find it.', 'kindness'),
  ('Pay a small kindness forward', 'Buy coffee, leave a tip, or cover a small cost for someone.', 'kindness'),
  ('Send an uplifting text', 'Text someone you appreciate and tell them why.', 'kindness'),
  ('Smile at five people', 'Offer a warm, genuine smile to five people you pass today.', 'kindness'),
  ('Thank a service worker', 'Thank someone who helps you daily and mean it.', 'kindness'),
  ('Offer your seat', 'Give your seat to someone who might need it more.', 'kindness'),
  ('Write three gratitudes', 'List three specific things you are grateful for today.', 'gratitude'),
  ('Thank your past self', 'Write one thing your past self did that you appreciate now.', 'gratitude'),
  ('Gratitude voice memo', 'Record a 30-second voice note of something good from today.', 'gratitude'),
  ('Appreciate your body', 'Thank one part of your body for what it does for you.', 'gratitude'),
  ('Thank a mentor', 'Message someone who taught you something valuable.', 'gratitude'),
  ('Evening gratitude pause', 'Before bed, name one moment that went well today.', 'gratitude'),
  ('Gratitude for food', 'Pause before a meal and appreciate where it came from.', 'gratitude'),
  ('Take a mindful walk', 'Walk ten minutes without your phone, noticing your surroundings.', 'health'),
  ('Drink an extra glass of water', 'Add one full glass of water to your usual intake today.', 'health'),
  ('Stretch for five minutes', 'Do a gentle five-minute stretch for your neck and shoulders.', 'health'),
  ('Go to bed earlier', 'Start your wind-down fifteen minutes earlier than usual.', 'health'),
  ('Eat one extra serving of vegetables', 'Add vegetables to one meal you already planned.', 'health'),
  ('Step outside for fresh air', 'Spend five minutes outdoors without multitasking.', 'health'),
  ('One-minute breathing break', 'Breathe slowly: inhale four counts, exhale six counts, one minute.', 'health'),
  ('Call someone you miss', 'Call a friend or family member just to check in.', 'connection'),
  ('Ask a deeper question', 'Ask someone how they are really doing and listen.', 'connection'),
  ('Share a positive memory', 'Tell someone a happy memory you share with them.', 'connection'),
  ('Write to an old friend', 'Send a message to someone you have not talked to in a while.', 'connection'),
  ('Plan a mini hangout', 'Suggest a short walk or coffee with someone this week.', 'connection'),
  ('Listen without fixing', 'In one conversation, listen fully without giving advice.', 'connection'),
  ('Express appreciation face to face', 'Tell someone in person one thing you value about them.', 'connection'),
  ('One minute of stillness', 'Sit quietly for one minute with no inputs.', 'mindfulness'),
  ('Notice five senses', 'Name one thing you see, hear, smell, taste, and feel.', 'mindfulness'),
  ('Mindful dishwashing', 'Wash dishes slowly, feeling the water and texture.', 'mindfulness'),
  ('Label your emotion', 'Pause and name your current emotion without judging it.', 'mindfulness'),
  ('Single-task for ten minutes', 'Do one small task with full attention, no switching.', 'mindfulness'),
  ('Gratitude walk', 'On a short walk, notice three small beautiful details.', 'mindfulness'),
  ('Body scan check-in', 'Scan from head to toe and relax one tense area.', 'mindfulness'),
  ('Pick up litter', 'Collect a few pieces of litter on your route today.', 'community'),
  ('Support a local business', 'Buy something small from a local shop or maker.', 'community'),
  ('Donate an item', 'Give one usable item you no longer need to someone who can use it.', 'community'),
  ('Share a helpful resource', 'Send a useful link or tip to someone who needs it.', 'community'),
  ('Volunteer thirty minutes', 'Spend half an hour helping a cause or neighbor task.', 'community'),
  ('Leave a positive review', 'Write a honest, kind review for a small business you like.', 'community'),
  ('Introduce two people', 'Connect two people who could help each other.', 'community'),
  ('Reduce single-use plastic', 'Use a reusable bag, bottle, or container once today.', 'environment'),
  ('Shorten your shower', 'Take a shower two minutes shorter than usual.', 'environment'),
  ('Walk instead of drive', 'Replace one short car trip with walking if possible.', 'environment'),
  ('Turn off unused lights', 'Switch off lights in rooms you are not using.', 'environment'),
  ('Say no kindly', 'Decline one request clearly and respectfully.', 'self-care'),
  ('Take a real break', 'Step away from screens for fifteen minutes guilt-free.', 'self-care'),
  ('Celebrate a small win', 'Acknowledge one thing you did well today, out loud.', 'self-care');
